### ISSUE TITLE
Sesame-2.8 / RDF-1.1 changes

### ISSUE THREAD

**Issue by ansell** [joshsh/sesametools#41]
As discussed in #37 , now that Sesame-2.8.0 is released, we can think about the design of SesameTools-2 (assuming that it would be a useful strategy to keep the RDF-1.0 code separate from the RDF-1.1 code).

The two RDF-1.1 changes are the removal of plain literals, which are now always typed with xsd:string, and the addition of rdf:langString as the datatype internally for language tagged literals.

The main non-RDF-1.1 changes are the introduction of transaction isolation levels and changes in dependencies, including the apache httpclient library that may have other dependency effects.

**Comment by joshsh** [comment]
Thanks, @ansell.  I have created a branch for this:
    https://github.com/joshsh/sesametools/tree/sesame-2.8

**Comment by joshsh** [comment]
Closing; migration to RDF 1.1 and Sesame 4 was the subject of the 1.10 release.  2.0 will use RDF4J.
